name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Bump version and tag
        uses: anothrNick/github-tag-action@v1
        id: bump_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: minor
          INITIAL_VERSION: '0.0.0'
          WITH_V: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.bump_version.outputs.new_tag }}
            ${{ github.ref == 'refs/heads/master' && format('ghcr.io/{0}:latest', github.repository) }}
          build-args: |
            TARGETOS=linux
            TARGETARCH=amd64
          platforms: linux/amd64, linux/arm64
